using System;

namespace trakit.objects {
	/// <summary>
	/// The type of logged message.
	/// </summary>
	/// <category>Behaviours</category>
	public enum BehaviourLogType : byte {
		/// <summary>
		/// Used for general information messages.
		/// </summary>
		log,
		/// <summary>
		/// Used for more important messages.
		/// </summary>
		info,
		/// <summary>
		/// Used for warnings.
		/// </summary>
		warn,
		/// <summary>
		/// Used for errors.
		/// </summary>
		err,
	}

	/// <summary>
	/// A debug message available to script writers to help debug and trace output from a BehaviourScript.
	/// </summary>
	/// <category>Behaviours</category>
	public class BehaviourLog : Subscribable, IIdUlong, IBelongCompany, IBelongAsset {
		/// <summary>
		/// Unique identifier of this log message.
		/// </summary>
		public ulong id { get; set; }
		/// <summary>
		/// The asset which whose behaviours created this log entry.
		/// </summary>
		/// <seealso cref="Asset.id" />
		public ulong asset { get; set; }
		/// <summary>
		/// The company to which this log message belongs.
		/// </summary>
		/// <seealso cref="Company.id" />
		public ulong company { get; set; }
		/// <summary>
		/// The behaviour to which this log message belongs.
		/// </summary>
		/// <seealso cref="Behaviour.id" />
		public ulong? behaviour { get; set; }
		/// <summary>
		/// The script which generated this log message.
		/// </summary>
		/// <seealso cref="BehaviourScript.id" />
		public ulong script { get; set; }
		/// <summary>
		/// The category of message.
		/// </summary>
		public BehaviourLogType kind;
		/// <summary>
		/// When the log entry was generated by the script.
		/// </summary>
		public DateTime dts;
		/// <summary>
		/// The body of the message.
		/// </summary>
		public string message;
		/// <summary>
		/// The line number of the script which generated this message.
		/// </summary>
		public uint line;
		/// <summary>
		/// The character column where the error was generated.
		/// </summary>
		public uint? character;
	}
}