using System;

namespace trakit.objects {
	/// <summary>
	/// Determines when and how often a report schedule runs automatically.
	/// </summary>
	public class ReportRecurrence {
		/// <summary>
		/// How often the report is automatically run.  Daily, weekly, monthly, etc...
		/// </summary>
		public ReportRecurrenceType kind;
		/// <summary>
		/// Used only for daily schedules, this 7 item, boolean array, determines if the schedule should recur on that day of the week.
		/// </summary>
		/// <override count="7" />
		public bool[]? weekdays;
		/// <summary>
		/// Used only for weekly schedules, it's a number between 0 and 6 representing the day of the week, with Sunday being the first day of the week.
		/// </summary>
		public byte? weekday;
		/// <summary>
		/// The local timezone used to calculate recurring date/time ranges.
		/// </summary>
		/// <seealso cref="Timezone.code" />
		/// <override type="System.String" format="codified" />
		[Obsolete("Use owner.timezone instead")]
		public TimeZoneInfo timezone;
		/// <summary>
		/// When the schedule is to begin recurring in local-time (not UTC).
		/// </summary>
		public DateTime start;
		/// <summary>
		/// The optional time when the schedule stops recurring in local-time (not UTC).
		/// </summary>
		public DateTime? end;

		// keeping track of progress
		/// <summary>
		/// The number of times this schedule has been invoked to generate results.
		/// </summary>
		/// <override readonly="true" />
		public ushort iterations;
		/// <summary>
		/// The unique identifier of the last ReportResult generated by this schedule.
		/// </summary>
		/// <override readonly="true" />
		public ulong? lastResult;
		/// <summary>
		/// This date/time is used as the startDate ReportParameter for the next iteration of this recurring report.
		/// This value is null when the schedule is calculated to stop recurring.
		/// </summary>
		/// <override readonly="true" />
		public DateTime? nextStartDate;
		/// <summary>
		/// This date/time is used as the endDate ReportParameter for the next iteration of this recurring report.
		/// This value is null when the schedule is calculated to stop recurring.
		/// </summary>
		/// <override readonly="true" />
		public DateTime? nextEndDate;
		/// <summary>
		/// The date/time stamp from the last result used to inform the nextStartDate and nextEndDate properties.
		/// This value is null when the schedule has not yet run once.
		/// </summary>
		/// <override readonly="true" />
		public DateTime? lastStartDate;
		/// <summary>
		/// The date/time stamp from the last result used to inform the nextStartDate and nextEndDate properties.
		/// This value is null when the schedule has not yet run once.
		/// </summary>
		/// <override readonly="true" />
		public DateTime? lastEndDate;
	}
}